import './globals.css';
import { Architects_Daughter } from '@next/font/google';
import Provider from './context/AuthContext';
import ToasterContext from './context/ToasterContext';
import { Header } from './components';

const archidaught = Architects_Daughter ({ weight: "400", subsets: ["latin"]}),

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archidaught.className}><Provider><ToasterContext />{children}</Provider></body>
    </html>
  )
}
