import './globals.css';
import { archidaught } from '../Utils/fonts.jsx';
import Provider from './context/AuthContext';
import ToasterContext from './context/ToasterContext';
import { Header } from './components';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archidaught.className}><Provider><ToasterContext />{children}</Provider></body>
    </html>
  )
}
